# Generated by Django 5.0.1 on 2024-02-26 18:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0003_alter_book_order_alter_order_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='order',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='orders.order'),
        ),
    ]
