# Generated by Django 4.2.10 on 2024-03-06 18:33

from django.db import migrations, models
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0005_remove_book_order_order_price_alter_book_available_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='description',
            field=tinymce.models.HTMLField(),
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.IntegerField(choices=[(1, 'Created'), (2, 'In process'), (3, 'Sended'), (4, 'Completed')]),
        ),
    ]
